---
title       : Data product assign 
subtitle    : Shiny Activity Object Detection App
author      : suleman
job         : student
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---

## Shiny App

Now you can detect User behavior using shiny app.

You can

1) Know where user is clicking.

2) Which action user is interested

3) Extreme data science algorithms which infer user behavior

---

## Application

1) In Marketing: Knowing user behavior you can increase your daily sell 1000%

2) In security: No user can silently get your things out of your reach. You will get an alarm immediately

3) In Strategy: You can develop great strategy knowing everything in advance

---

## Price

We have a trial service, just try our product 1 month freely

Packages start from

1) $2 Baby package

2) $5 Mature Package

3) $10 Enterprenuer package

----

## Feedback:

We like to hear from you about activity detection shiny app

feel free to mail us at activity_detection@shiny.com

## Contact us

Want to chat, mail or call us. 24Hours.activity_detection@shiny.com




